# Generated by Django 5.0 on 2025-11-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="상품 ID"
                    ),
                ),
                ("product_type", models.CharField(max_length=50, verbose_name="상품 타입")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="가격"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="원가"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="할인율"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="기록 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "가격 이력",
                "verbose_name_plural": "가격 이력",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["product_id", "-recorded_at"],
                        name="products_pr_product_84f8c9_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="products_pr_recorde_b1d7b3_idx"
                    ),
                ],
            },
        ),
    ]
