# Generated by Django 5.2.8 on 2025-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coatproduct',
            name='material_composition',
            field=models.TextField(blank=True, help_text='예: polyester 40%, acrylic 20%, wool 4%', null=True, verbose_name='소재 구성'),
        ),
        migrations.AddField(
            model_name='crewneckproduct',
            name='material_composition',
            field=models.TextField(blank=True, help_text='예: polyester 40%, acrylic 20%, wool 4%', null=True, verbose_name='소재 구성'),
        ),
        migrations.AddField(
            model_name='downproduct',
            name='material_composition',
            field=models.TextField(blank=True, help_text='예: polyester 40%, acrylic 20%, wool 4%', null=True, verbose_name='소재 구성'),
        ),
        migrations.AddField(
            model_name='genericproduct',
            name='material_composition',
            field=models.TextField(blank=True, help_text='예: polyester 40%, acrylic 20%, wool 4%', null=True, verbose_name='소재 구성'),
        ),
        migrations.AddField(
            model_name='jeansproduct',
            name='material_composition',
            field=models.TextField(blank=True, help_text='예: polyester 40%, acrylic 20%, wool 4%', null=True, verbose_name='소재 구성'),
        ),
        migrations.AddField(
            model_name='longsleeveproduct',
            name='material_composition',
            field=models.TextField(blank=True, help_text='예: polyester 40%, acrylic 20%, wool 4%', null=True, verbose_name='소재 구성'),
        ),
        migrations.AddField(
            model_name='slacksproduct',
            name='material_composition',
            field=models.TextField(blank=True, help_text='예: polyester 40%, acrylic 20%, wool 4%', null=True, verbose_name='소재 구성'),
        ),
    ]
