# Generated by Django 5.0 on 2025-11-21 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254, verbose_name='수신자')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('body_html', models.TextField(verbose_name='내용 (HTML)')),
                ('reason', models.CharField(choices=[('price_drop', '가격 하락'), ('restock', '재입고')], max_length=50, verbose_name='알림 사유')),
                ('product_id', models.CharField(max_length=100, verbose_name='상품 ID')),
                ('product_data', models.JSONField(verbose_name='상품 스냅샷')),
                ('sent', models.BooleanField(db_index=True, default=False, verbose_name='발송 완료')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시각')),
                ('error', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '이메일 큐',
                'verbose_name_plural': '이메일 큐',
                'indexes': [models.Index(fields=['sent', 'created_at'], name='alerts_emai_sent_6894a3_idx'), models.Index(fields=['to_email'], name='alerts_emai_to_emai_72663b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='이메일')),
                ('conditions', models.JSONField(default=dict, verbose_name='알림 조건')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand', verbose_name='브랜드')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '가격 알림',
                'verbose_name_plural': '가격 알림',
                'indexes': [models.Index(fields=['active', 'brand', 'category'], name='alerts_aler_active_3a8730_idx'), models.Index(fields=['email', 'active'], name='alerts_aler_email_454615_idx')],
            },
        ),
    ]
