# Generated by Django 5.2.8 on 2025-11-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alerthistory_alertstatistics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='alerts_aler_alert_i_7595f3_idx',
            old_name='alerts_aler_alert_i_idx',
        ),
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='alerts_aler_product_66cf54_idx',
            old_name='alerts_aler_product_idx',
        ),
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='alerts_aler_email_s_4a01ef_idx',
            old_name='alerts_aler_email_s_idx',
        ),
        migrations.RenameIndex(
            model_name='alertstatistics',
            new_name='alerts_aler_alert_i_055ad5_idx',
            old_name='alerts_aler_alert_d_idx',
        ),
        migrations.RenameIndex(
            model_name='alertstatistics',
            new_name='alerts_aler_date_435247_idx',
            old_name='alerts_aler_date_idx',
        ),
        migrations.RenameIndex(
            model_name='emailqueue',
            new_name='alerts_emai_alert_i_e15b3a_idx',
            old_name='alerts_emai_alert_c_idx',
        ),
    ]
