# Generated by Django 5.0 on 2025-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='브랜드명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 슬러그')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='로고 URL')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_brand_slug_bb0dea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 슬러그')),
                ('category_type', models.CharField(choices=[('down', '다운'), ('slacks', '슬랙스'), ('jeans', '청바지'), ('crewneck', '크루넥'), ('long-sleeve', '긴팔'), ('coat', '코트'), ('generic', '기타')], default='generic', max_length=50, verbose_name='카테고리 유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_catego_slug_a504e5_idx'), models.Index(fields=['category_type'], name='core_catego_categor_da3d25_idx')],
            },
        ),
    ]
