# Generated by Django 5.2.8 on 2025-11-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, help_text='기준 상품 ID', max_length=50, unique=True)),
                ('recommended_product_ids', models.JSONField(help_text='추천 상품 ID 리스트')),
                ('scores', models.JSONField(help_text='추천 점수 리스트')),
                ('algorithm', models.CharField(help_text='사용된 알고리즘 (cf, popular, hybrid)', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터 (계산 시간, 샘플 수 등)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '추천 캐시',
                'verbose_name_plural': '추천 캐시',
                'db_table': 'recommendation_cache',
            },
        ),
        migrations.CreateModel(
            name='UserProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='익명 사용자 세션 ID', max_length=255)),
                ('user_email', models.EmailField(blank=True, db_index=True, help_text='등록 사용자 이메일', max_length=254, null=True)),
                ('product_id', models.CharField(db_index=True, help_text='상품 ID', max_length=50)),
                ('product_category', models.CharField(db_index=True, help_text='상품 카테고리', max_length=50)),
                ('product_brand', models.CharField(help_text='상품 브랜드', max_length=100)),
                ('interaction_type', models.CharField(choices=[('view', '조회'), ('click', '클릭'), ('alert', '알림'), ('purchase', '구매')], default='view', help_text='상호작용 유형', max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='가중치 (view=0.5, click=1.0, alert=1.5, purchase=3.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '사용자-상품 상호작용',
                'verbose_name_plural': '사용자-상품 상호작용',
                'db_table': 'user_product_interactions',
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='user_produc_session_6c43cb_idx'), models.Index(fields=['product_id', 'interaction_type'], name='user_produc_product_05affc_idx'), models.Index(fields=['product_category', 'created_at'], name='user_produc_product_8721fd_idx')],
            },
        ),
    ]
