# Generated by Django 5.2.8 on 2025-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, help_text='상품 ID', max_length=100, unique=True)),
                ('image_url', models.URLField(help_text='원본 이미지 URL', max_length=2000)),
                ('embedding_vector', models.JSONField(help_text='2048차원 벡터 (JSON array)')),
                ('model_version', models.CharField(default='resnet50', help_text='사용된 모델 버전', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '이미지 임베딩',
                'verbose_name_plural': '이미지 임베딩',
                'db_table': 'image_embeddings',
                'indexes': [models.Index(fields=['product_id', 'created_at'], name='image_embed_product_e4f01b_idx'), models.Index(fields=['model_version', '-created_at'], name='image_embed_model_v_11494b_idx')],
            },
        ),
    ]
