# Generated by Django 5.0 on 2025-11-21 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=100, verbose_name='상품 ID')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('referrer', models.CharField(blank=True, max_length=200, null=True, verbose_name='유입 경로')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='사용자 에이전트')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='클릭 시각')),
            ],
            options={
                'verbose_name': '클릭 추적',
                'verbose_name_plural': '클릭 추적',
                'indexes': [models.Index(fields=['timestamp'], name='analytics_c_timesta_d63331_idx'), models.Index(fields=['product_id', 'timestamp'], name='analytics_c_product_e0d611_idx'), models.Index(fields=['brand', 'category', 'timestamp'], name='analytics_c_brand_4ff736_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyClickAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='날짜')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('click_count', models.IntegerField(default=0, verbose_name='클릭 수')),
                ('unique_products', models.IntegerField(default=0, verbose_name='고유 상품 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '일일 클릭 집계',
                'verbose_name_plural': '일일 클릭 집계',
                'indexes': [models.Index(fields=['date', 'brand', 'category'], name='analytics_d_date_0f8c3c_idx')],
                'unique_together': {('date', 'brand', 'category')},
            },
        ),
    ]
